# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-08 02:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reddit', '0009_auto_20170507_0940'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='on_post',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='reddit.Post'),
        ),
    ]
